### ISSUE TITLE
Use of CDR3-alpha + CDR3-beta pairs

### ISSUE THREAD

**Issue by snaketron** [HetzDra/turboGliph#1]
In a single cell design we get for each cell a pair of alpha and beta TCR chains.

gliph (and also turboGliph) appears to use only CDR3-beta. Is this correct?

Best,
Simo

**Comment by HetzDra** [comment]
Your understanding is correct. turboGliph is a much faster implementation of the GLIPH algorithm. Since the original algorithm was developed only for CDR3beta sequences, turboGliph can currently also only handle CDR3beta sequences. It is planned to extend the basic principle of turboGliph to a joint analysis of CDR3beta and -alpha sequences in the future, but currently this is not possible.

Best regards,

Jan

**Comment by snaketron** [comment]
Thank you!
