### ISSUE TITLE
Mouse reference dataset for gliph or gliph2

### ISSUE THREAD

**Issue by canuckafar** [HetzDra/turboGliph#3]
Thank you for making turboGliph available to others!  I have encountered an issue when I try to use either the **turbo_gliph** or **gliph2** algorithm on mouse TCR sequences. My dataset has 313,847 unique TCR sequences from 8 organ sites in 7 mice. I wanted to use gliph to cluster the TCRs.

When I format the data, it looks like this.

```
> head(tcr_gliph)
# A tibble: 6 × 6
  CDR3b              TRBV     TRBJ    counts HLA   patient             
  <chr>              <chr>    <chr>    <dbl> <chr> <chr>               
1 CASGDRAPSGNTLYF    TRBV13-2 TRBJ1-3     66 H-2KB Mouse1:symphonyblood
2 CASSQGYSDYTF       TRBV12-2 TRBJ1-2     52 H-2KB Mouse1:symphonyblood
3 CASSLELGGREQYF     TRBV16-1 TRBJ2-7     43 H-2KB Mouse1:symphonyblood
4 CASSAGTGGNYEQYF    TRBV12-2 TRBJ2-7     42 H-2KB Mouse1:symphonyblood
5 CASSLGTGGARVYAEQFF TRBV12-1 TRBJ2-1     42 H-2KB Mouse1:symphonyblood
6 CASSDRGTEVFF       TRBV13-1 TRBJ1-1     40 H-2KB Mouse1:symphonyblood
 
```
When I pass this data frame to the **turbo_gliph** function I get the following error:

```
gl1 <- turbo_gliph(cdr3_sequences = tcr_gliph,
                    result_folder = '../data/meta/gliph1',
                    sim_depth = 1000,
                    n_cores = 16)
Notification: cdr3_sequences is a data frame and the column named "CDR3b" is considered as cdr3 beta sequences.
Part 1: Searching for motifs in the data and reference DB. 
Error in turbo_gliph(cdr3_sequences = tcr_gliph, result_folder = "../data/meta/gliph1",  : 
  Analysis failed. Reference database must have more sequences than input data for the significance analysis to make sense and work.
```

This seems to suggest that the reference dataset is not appropriate for my data. Any suggestions?

**Comment by HetzDra** [comment]
Dear @canuckafar,

Thank you for your interest in using **turboGliph** and sorry for the delayed reply.
Regarding your request, there are two points to mention:

1. The reference database included in the package is the same as the reference database in the original publication of GLIPH, which includes only human CDR3b sequences. This database is not suitable for the analysis of murine data. With the publication of GLIPH2, other databases representing murine CD4 (~20E3), CD8 (~50E3), or CD48 (~70E3) T cells were published. (http://50.255.35.37:8080/tools) These are strongly recommended at this point for analysis of murine data.

2. For the statistics of the **turbo_gliph** function, it is essential that the reference database contains significantly more sequences than the sample, since subsampling without replacement is performed. For this reason, the analysis cannot be performed with a reference database of less size than the input data. In the **gliph2** function, it is not necessary for the algorithm that the reference database is larger. But again, for a correct statistical evaluation of the input data, the reference database should be larger. I have updated the *gliph2* function, so that no more error is output, but instead a warning and the calculation can be performed. However, I must emphasize that the statistical rigidity of the analysis requires a larger reference database. 

I hope your questions could be answered. For further questions, do not hesitate to contact us.

Best regards,
Jan

**Comment by canuckafar** [comment]
Thank you for the prompt and detailed response. I was able to use GLIPH2 on the website you linked without issue. It was pretty fast too. Now I just have to figure out how to best use this cluster information!
